### ISSUE TITLE
obtain training and test data for traffic light classifier

### ISSUE THREAD

**Issue by dhlong** [9mat/CarND-Capstone#5]

**Comment by dhlong** [comment]
after having tf_detector done, need to run the simulator to capture more training & testing images for the classifier

**Comment by xingjin2017** [comment]
Not necessarily for this class, it would be interesting if you can get the VIVA traffic light dataset:

https://github.com/9mat/CarND-Capstone/issues/5#issuecomment-335852928

:)

**Comment by xingjin2017** [comment]
http://cvrr.ucsd.edu/vivachallenge/index.php/traffic-light/traffic-light-detection/
